# Для локального тестирования
services:
  nginx: 
    image: nginx:stable-alpine
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./certs:/etc/nginx/certs
      - ./nginx-local.conf:/etc/nginx/nginx.conf
    networks:
      - test

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - pg_test
    environment:
      - ADMINER_DESIGN=pepa-linha-dark
    networks:
      - test
      
  frontend: 
    depends_on:
      - backend 
    ports: 
      - "3000"
    build: 
      context: ./frontend
      dockerfile: Dockerfile.local
    networks:
      - test
        
  backend: 
    depends_on:
      - pg_test
      - redis_test
    ports:
      - "127.0.0.1:8001:8000"
    restart: unless-stopped
    build: 
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      REDIS__HOST: redis_test
      REDIS__PORT: 6379
      DB__HOST: pg_test
      DB__PORT: 5432
    volumes:
      - ./backend/chrome-linux64.zip:/backend/chrome-linux64.zip:ro
      - ./backend/chromedriver-linux64.zip:/backend/chromedriver-linux64.zip:ro
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    networks:
      - test
  pg_test:
    image: postgres:17
    restart: unless-stopped
    ports:
      - "127.0.0.1:5435:5432" # локальный порт:порт контейнера
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB__USER}
      POSTGRES_DB: ${DB__NAME}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
    volumes:
      - pg-test-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    networks:
      - test

  redis_test:
    image: redis:7
    restart: unless-stopped
    ports:
      - "127.0.0.1:6381:6379"
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS__PASSWORD}
    command:
      - redis-server
      - --requirepass
      - ${REDIS__PASSWORD}
    volumes:
      - redis-test-data:/data
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
    networks:
      - test
  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    depends_on:
      - nginx
      - pg_test
      - redis_test
    ports:
      - "127.0.0.1:9000:9000" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # дает доступ к docker
      - portainer_data:/data 
    networks:
      - test  

networks:
  test:
    driver: bridge

volumes:
  pg-test-data:
  redis-test-data:
  portainer_data: