# Generally set to be equal to the number of CPUs or cores.
worker_processes  2;

error_log /var/log/nginx/access.log;


events {
    worker_connections  1024;
    multi_accept on;
}


http {
    include       mime.types;
    # anything written in /opt/nginx/conf/mime.types is interpreted as if written inside the http { } block

    default_type  application/octet-stream;

    log_format  custom  '$remote_addr - $remote_user [$time_local] "$request" '
                     '$status $body_bytes_sent "$http_referer" '
                     '"$http_user_agent" "$http_x_forwarded_for"';

    # rotate the access log when it grows beyond 1 MB and keep the last 3 files
    access_log /var/log/nginx/access.log custom;  
    

    sendfile        on;
    client_max_body_size 12M;

    limit_req_zone $binary_remote_addr zone=api:10m rate=30r/s;

    # how much to keep connection with client alive (seconds) 
    keepalive_timeout  65;
    keepalive_requests 100;


    gzip  on;
    server_tokens off;

    server {
        listen 80;

        server_name localhost;
            
        return 301 https://$host$request_uri;
    }

    server {
        listen       443 ssl;

        server_name localhost;


        location / {
            proxy_pass http://frontend:3000/;
        }

        location = /api {
            return 301 /api/;
        }

        location /api/ {
            limit_req zone=api burst=50;
            proxy_pass http://backend:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }



        ssl_certificate ./certs/192.168.04+2.pem;
        ssl_certificate_key ./certs/localhost+2-key.pem;
    }

}