# Generally set to be equal to the number of CPUs or cores.
worker_processes  2;

error_log /var/log/nginx/access.log;

events {
    worker_connections  1024;
    multi_accept on;
}


http {
    include       mime.types;
    # anything written in /opt/nginx/conf/mime.types is interpreted as if written inside the http { } block

    default_type  application/octet-stream;

    log_format  custom  '$remote_addr - $remote_user [$time_local] "$request" '
                     '$status $body_bytes_sent "$http_referer" '
                     '"$http_user_agent" "$http_x_forwarded_for"';

    # rotate the access log when it grows beyond 1 MB and keep the last 3 files
    access_log /var/log/nginx/access.log custom;  
    

    sendfile        on;
    client_max_body_size 12M;

    limit_req_zone $binary_remote_addr zone=api:10m rate=30r/s;

    # how much to keep connection with client alive (seconds) 
    keepalive_timeout  65;
    keepalive_requests 100;


    gzip  on;
    server_tokens off;

    server {
        listen 80;

        server_name 
            paragraph-schedule.ru 
            www.paragraph-schedule.ru 
            api.paragraph-schedule.ru
            www.api.paragraph-schedule.ru;
            
        return 301 https://$host$request_uri;
    }

    server {
        listen       443 ssl;

        server_name  
            paragraph-schedule.ru 
            www.paragraph-schedule.ru;



        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        
        location / {
            proxy_pass http://frontend:3000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location = /sitemap.xml {
            root /var/www/html/site;
            try_files /sitemap.xml =404;
        }

        location = /robots.txt {
            root /var/www/html/site;
            try_files /robots.txt =404;
        }


        ssl_certificate /etc/letsencrypt/live/paragraph-schedule.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/paragraph-schedule.ru/privkey.pem;
    }


    server {
        listen       443 ssl;

        server_name  
            api.paragraph-schedule.ru 
            www.api.paragraph-schedule.ru; 


        location / {
            limit_req zone=api burst=50;
            proxy_pass http://backend:8000/;
        }

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }


        ssl_certificate /etc/letsencrypt/live/api.paragraph-schedule.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/api.paragraph-schedule.ru/privkey.pem;
    }

}