reload-db:
	poetry run python -m backend.api.scripts.reload_db

# refresh-db:
# 	poetry run python -m backend.api.scripts.reload_db --refresh

reload-test-db:
	poetry run python -m backend.api.scripts.reload_db --test

refresh-test-db:
	poetry run python -m backend.api.scripts.reload_db  --test --refresh

