"""association

Revision ID: 21d9046bf441
Revises: e7121f639ab1
Create Date: 2025-11-14 11:39:16.994268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21d9046bf441'
down_revision: Union[str, Sequence[str], None] = 'e7121f639ab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dates_id'), 'dates', ['id'], unique=False)
    op.create_table('group_date_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('dates_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dates_id'], ['dates.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'dates_id', name='index')
    )
    op.add_column('homeworks', sa.Column('text', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homeworks', 'text')
    op.drop_table('group_date_association')
    op.drop_index(op.f('ix_dates_id'), table_name='dates')
    op.drop_table('dates')
    # ### end Alembic commands ###
