"""empty message

Revision ID: 47e93a757468
Revises: 597f03e6d447
Create Date: 2025-12-10 20:31:26.041878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47e93a757468'
down_revision: Union[str, Sequence[str], None] = '597f03e6d447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_group_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('users_group_id_fkey'), 'users', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###
