"""removed unuqieconstr

Revision ID: 7f908c4c9505
Revises: f39bbae3993e
Create Date: 2025-12-09 22:59:10.042627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f908c4c9505'
down_revision: Union[str, Sequence[str], None] = 'f39bbae3993e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('index_unique_group_date'), 'group_date_association', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('index_unique_group_date'), 'group_date_association', ['group_id', 'dates_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
