"""renamed gr_dt_ass to homework and added user_id fk

Revision ID: 8efb09964502
Revises: 25c53ddd71b5
Create Date: 2026-01-15 19:45:31.479855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8efb09964502'
down_revision: Union[str, Sequence[str], None] = '25c53ddd71b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homework',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('dates_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson', sa.Integer(), nullable=True),
    sa.Column('homework', sa.String(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dates_id'], ['dates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('group_date_association')
    op.alter_column('users', 'sign_up_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'sign_up_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.create_table('group_date_association',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dates_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lesson', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('homework', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dates_id'], ['dates.id'], name=op.f('group_date_association_dates_id_fkey')),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('group_date_association_group_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('group_date_association_pkey'))
    )
    op.drop_table('homework')
    # ### end Alembic commands ###
