"""empty message

Revision ID: b870f53dc89f
Revises: 21d9046bf441
Create Date: 2025-11-14 13:22:24.764039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b870f53dc89f'
down_revision: Union[str, Sequence[str], None] = '21d9046bf441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('index'), 'group_date_association', type_='unique')
    op.create_unique_constraint('index_unique_group_date', 'group_date_association', ['group_id', 'dates_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('index_unique_group_date', 'group_date_association', type_='unique')
    op.create_unique_constraint(op.f('index'), 'group_date_association', ['group_id', 'dates_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
