"""added sign_up_date field to users table

Revision ID: bc0d34ae04ca
Revises: 8280be2c9762
Create Date: 2026-01-07 01:47:16.498614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc0d34ae04ca'
down_revision: Union[str, Sequence[str], None] = '8280be2c9762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sign_up_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sign_up_date')
    # ### end Alembic commands ###
