"""made is_note field nullable

Revision ID: 03bad67fd893
Revises: 8b1b656f91f9
Create Date: 2026-03-19 22:21:50.473499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03bad67fd893'
down_revision: Union[str, Sequence[str], None] = '8b1b656f91f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('homework', 'is_note',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('homework', 'is_note',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
