"""add notes field to homework table

Revision ID: 2560833095f4
Revises: 3a4acdc43a87
Create Date: 2026-03-19 11:10:31.389957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2560833095f4'
down_revision: Union[str, Sequence[str], None] = '3a4acdc43a87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homework', sa.Column('is_note', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homework', 'is_note')
    # ### end Alembic commands ###
