"""fix homework table field names

Revision ID: 8b1b656f91f9
Revises: 2560833095f4
Create Date: 2026-03-19 11:31:15.270788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b1b656f91f9'
down_revision: Union[str, Sequence[str], None] = '2560833095f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homework', sa.Column('lesson_index', sa.Integer(), nullable=True))
    op.add_column('homework', sa.Column('homework_text', sa.String(), nullable=True))
    op.drop_column('homework', 'lesson')
    op.drop_column('homework', 'homework')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homework', sa.Column('homework', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('homework', sa.Column('lesson', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('homework', 'homework_text')
    op.drop_column('homework', 'lesson_index')
    # ### end Alembic commands ###
