"""added updated column

Revision ID: 8eb1f33b1165
Revises: 7f908c4c9505
Create Date: 2025-12-10 17:09:42.181385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8eb1f33b1165'
down_revision: Union[str, Sequence[str], None] = '7f908c4c9505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_date_association', sa.Column('updated', sa.DateTime(), nullable=True))
    op.drop_column('group_date_association', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_date_association', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('group_date_association', 'updated')
    # ### end Alembic commands ###
