"""changed users table

Revision ID: a4f021934724
Revises: 4fcedccd9db0
Create Date: 2025-12-30 00:01:12.132410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4f021934724'
down_revision: Union[str, Sequence[str], None] = '4fcedccd9db0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=False))
    op.drop_column('users', 'rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('users', 'active')
    # ### end Alembic commands ###
